# Generated by Django 6.0.6 on 2026-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('DOCTOR', 'Doctor')]),
        ),
    ]
