# Generated by Django 6.0.6 on 2026-06-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Bemor arizasi matni')),
                ('doctor_response', models.TextField(blank=True, null=True, verbose_name='Shifokor tashxisi/javobi')),
                ('operator_response', models.TextField(blank=True, null=True, verbose_name='Operator izohi')),
                ('status', models.CharField(choices=[('NEW', 'Yangi (Operator kutilmoqda)'), ('ASSIGNED', 'Shifokor biriktirildi'), ('REJECTED', 'Rad etildi'), ('COMPLETED', 'Yakunlandi (Shifokor javob berdi)')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
            },
        ),
    ]
