# Generated by Django 6.0.6 on 2026-06-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Operator kutilmoqda)'), ('ASSIGNED', 'Shifokor biriktirildi'), ('REJECTED', 'Rad etildi'), ('COMPLETED', 'Yakunlandi (Shifokor javob berdi)'), ('CLOSED', 'Yopildi (Bemorga javob yuborildi)')], default='NEW', max_length=20),
        ),
    ]
