# Generated by Django 6.0.6 on 2026-06-26 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_applications_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='rejected_by_doctors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'DOCTOR'}, related_name='skipped_applications', to=settings.AUTH_USER_MODEL, verbose_name='Ushbu arizani rad etgan shifokorlar'),
        ),
    ]
