# Generated by Django 6.0.6 on 2026-06-27 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_applications_rejected_by_doctors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={},
        ),
        migrations.RemoveField(
            model_name='applications',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='doctor_response',
        ),
        migrations.AlterField(
            model_name='applications',
            name='rejected_by_doctors',
            field=models.ManyToManyField(blank=True, related_name='skipped_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Operator kutilmoqda)'), ('ASSIGNED', 'Shifokor(lar) biriktirildi'), ('REJECTED', 'Rad etildi'), ('COMPLETED', 'Yakunlandi (Shifokorlar javob berdi)'), ('CLOSED', 'Yopildi (Bemorga javob yuborildi)')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_response', models.TextField(blank=True, null=True, verbose_name='Shifokorning shaxsiy tashxisi')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='application.applications')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('application', 'doctor')},
            },
        ),
        migrations.AddField(
            model_name='applications',
            name='doctors',
            field=models.ManyToManyField(related_name='doctor_applications', through='application.ApplicationAssignment', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan shifokorlar'),
        ),
    ]
