# Generated by Django 6.0.6 on 2026-06-27 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_applications_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='doctors',
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AddField(
            model_name='applications',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applications',
            name='doctor_response',
            field=models.TextField(blank=True, null=True, verbose_name='Shifokor tashxisi/javobi'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='rejected_by_doctors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'DOCTOR'}, related_name='skipped_applications', to=settings.AUTH_USER_MODEL, verbose_name='Ushbu arizani rad etgan shifokorlar'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Operator kutilmoqda)'), ('ASSIGNED', 'Shifokor biriktirildi'), ('REJECTED', 'Rad etildi'), ('COMPLETED', 'Yakunlandi (Shifokor javob berdi)'), ('CLOSED', 'Yopildi (Bemorga javob yuborildi)')], default='NEW', max_length=20),
        ),
        migrations.DeleteModel(
            name='ApplicationAssignment',
        ),
    ]
