# Generated by Django 6.0.6 on 2026-06-29 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_applications_doctors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='doctor_response',
        ),
        migrations.AddField(
            model_name='applications',
            name='user_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemor yuborgan fayl/rasm ID-si'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Operator kutilmoqda)'), ('ASSIGNED', 'Shifokor(lar) biriktirildi'), ('REJECTED', 'Rad etildi'), ('COMPLETED', 'Yakunlandi (Shifokorlar javob berdi)'), ('CLOSED', 'Yopildi (Bemorga javob yuborildi)')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_response_text', models.TextField(blank=True, null=True, verbose_name='Shifokor tashxisi/javobi')),
                ('doctor_response_file', models.FileField(blank=True, null=True, upload_to='doctor_responses/', verbose_name='Shifokor yuklagan hujjat/fayl (Sayt uchun)')),
                ('doctor_response_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shifokor yuborgan faylning Telegram ID-si (Bot uchun)')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqt')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='application.applications')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shifokor biriktiruvi',
                'verbose_name_plural': 'Shifokor biriktiruvlari',
                'unique_together': {('application', 'doctor')},
            },
        ),
        migrations.AddField(
            model_name='applications',
            name='doctors',
            field=models.ManyToManyField(related_name='doctor_applications', through='application.ApplicationAssignment', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan shifokorlar'),
        ),
    ]
