# Generated by Django 6.0.6 on 2026-06-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_applications_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='user_file_id',
        ),
        migrations.AddField(
            model_name='applications',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemor yuborgan fayl/rasm ID-si'),
        ),
    ]
