# Generated by Django 6.0.6 on 2026-06-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_applications_user_file_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['-pk'], 'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='file_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Bemor yuborgan fayl/rasm ID-si'),
        ),
    ]
