# Generated by Django 6.0.6 on 2026-06-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_applications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemor yuborgan fayl/rasm ID-si'),
        ),
    ]
