# Generated by Django 6.0.6 on 2026-06-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_applications_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='file_id',
        ),
        migrations.AddField(
            model_name='applications',
            name='user_file_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Bemor fayli havolasi'),
        ),
    ]
