# Generated by Django 6.0.6 on 2026-07-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_applications_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationassignment',
            name='doctor_response_file',
            field=models.FileField(blank=True, null=True, upload_to='doctor_responses//%Y/%m/%d/', verbose_name='Shifokor yuklagan hujjat/fayl (Sayt uchun)'),
        ),
    ]
