# Generated by Django 6.0.6 on 2026-07-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_applicationassignment_doctor_response_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationassignment',
            name='status',
            field=models.CharField(choices=[('UNSEEN', "Hali ko'rmadi"), ('ACCEPTED', 'Qabul qildi / Javob berdi'), ('REJECTED', 'Rad etdi (Atkaz)')], default='UNSEEN', max_length=20, verbose_name='Shifokor munosabati'),
        ),
    ]
