# Generated by Django 6.0.6 on 2026-07-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_applicationassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationassignment',
            name='doctor_response_file',
            field=models.FileField(blank=True, null=True, upload_to='doctor_responses/%Y/%m/%d/', verbose_name='Shifokor yuklagan hujjat/fayl (Sayt uchun)'),
        ),
    ]
