# Generated by Django 6.0.6 on 2026-07-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_applicationassignment_doctor_response_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='status',
        ),
    ]
