# Generated by Django 6.0.6 on 2026-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_remove_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationassignment',
            name='status',
            field=models.CharField(choices=[('UNSEEN', "Hali ko'rmadi"), ('ACCEPTED', 'Qabul qildi (Jarayonda)'), ('REJECTED', 'Rad etdi (Atkaz)'), ('RESPONDED', 'Javob berdi (Yakunlandi)')], default='UNSEEN', max_length=20, verbose_name='Shifokor munosabati'),
        ),
    ]
